-- Grupo 4 (Números 1-12)
INSERT INTO questions (number, question, image, answer, group_id, user_id) VALUES 
(1, '¿Qué significa que una variable sea aleatoria continua y por qué la presión arterial se considera un ejemplo de ello?', NULL, 'Una variable aleatoria continua puede tomar cualquier valor dentro de un rango; la presión arterial es continua porque, aunque la midamos en mmHg enteros, en el cuerpo varía de forma fluida y no en saltos discretos.', 1, 1),
(2, 'Si la presión arterial sistólica tiene una media de 120 mmHg y una desviación estándar de 15 mmHg, ¿qué porcentaje aproximado de la población tiene valores entre 90 y 150 mmHg?', NULL, 'Aproximadamente el 95%, porque 90 = 120 - 2×15 y 150 = 120 + 2×15, lo que corresponde a μ ± 2σ en una distribución normal.', 1, 1),
(3, '¿Por qué se dice que la distribución normal estándar tiene media 0 y desviación estándar 1, y cuál es su utilidad principal?', NULL, 'Porque resulta de estandarizar cualquier normal mediante Z = (X - μ)/σ; su utilidad es permitir comparar variables con unidades diferentes y usar una sola tabla de probabilidades.', 1, 1),
(4, '¿Qué representa un valor Z de -1.5 en el contexto de los niveles de hemoglobina en mujeres?', NULL, 'Que el nivel de hemoglobina está 1.5 desviaciones estándar por debajo de la media poblacional, lo que sugiere un valor bajo (posible anemia).', 1, 1),
(5, '¿Por qué en medicina se considera “anormal” un valor que está a más de 2 desviaciones estándar de la media en una distribución normal?', NULL, 'Porque solo el 5% de la población (aproximadamente) tiene valores fuera de ese rango (μ ± 2σ), lo que sugiere que podría estar asociado a una condición patológica.', 1, 1),
(6, '¿Qué diferencia hay entre un estadígrafo y un parámetro, y por qué es importante distinguirlos en investigación clínica?', NULL, 'Un estadígrafo describe una muestra; un parámetro describe una población. Es crucial porque los resultados muestrales se usan para inferir sobre la población, pero no son idénticos.', 1, 1),
(7, '¿Por qué se usa un modelo teórico como la curva normal en lugar de solo los datos reales de una muestra?', NULL, 'Porque suaviza la variabilidad aleatoria de la muestra, permite calcular probabilidades para cualquier valor y facilita la generalización a la población.', 1, 1),
(8, 'Si la probabilidad frecuencial de un evento es 0.25, ¿significa que ocurrirá exactamente una vez cada cuatro intentos?', NULL, 'No; 0.25 es una tendencia a largo plazo. En pocos intentos, la frecuencia observada puede variar mucho por azar.', 1, 1),
(9, '¿Qué tipo de muestreo se usa cuando se seleccionan pacientes al azar de un registro clínico, y por qué es preferible en investigación?', NULL, 'Muestreo probabilístico (aleatorio simple); es preferible porque garantiza representatividad y reduce el sesgo al dar a cada individuo la misma probabilidad de ser incluido.', 1, 1),
(10, '¿Por qué no es representativa una muestra obtenida entrevistando solo a pacientes que acuden un lunes por la mañana?', NULL, 'Porque no todos los pacientes tienen la misma probabilidad de ser seleccionados; los del lunes pueden ser distintos (ej.: jubilados), lo que introduce sesgo.', 1, 1),
(11, '¿Qué nos permite hacer la tabla de valores Z en el contexto de la distribución normal estándar?', NULL, 'Nos permite encontrar la probabilidad acumulada a la izquierda de un valor Z, es decir, el porcentaje de la población con valores menores que un dato dado.', 1, 1),
(12, 'Si un paciente tiene un valor Z de 2.0 en colesterol, ¿qué percentil ocupa aproximadamente y qué implica clínicamente?', NULL, 'Ocupa aproximadamente el percentil 97.5, lo que implica que su nivel es más alto que el 97.5% de la población y podría considerarse de alto riesgo.', 1, 1);

-- Grupo 5 (Números 13-24)
INSERT INTO questions (number, question, image, answer, group_id, user_id) VALUES 
(13, '¿Por qué la probabilidad clásica no es aplicable para estimar la prevalencia de diabetes en una población?', NULL, 'Porque la probabilidad clásica requiere resultados equiprobables (como en un dado), y la diabetes no tiene una probabilidad teórica conocida antes de observar datos.', 2, 1),
(14, 'Si la glucosa en ayunas tiene una media de 90 mg/dL y una desviación estándar de 10 mg/dL, ¿qué porcentaje de personas tiene valores entre 80 y 100 mg/dL?', NULL, 'Aproximadamente el 68%, porque 80 = 90 - 10 y 100 = 90 + 10, lo que corresponde a μ ± 1σ en una distribución normal.', 2, 1),
(15, 'Si un paciente tiene un valor Z de 0.8 en presión arterial sistólica, ¿está este valor dentro del rango considerado “normal” en medicina?', NULL, 'Sí, porque está a menos de 2 desviaciones estándar de la media (|Z| = 0.8 < 2), lo que lo ubica dentro del 95% central de la población.', 2, 1),
(16, '¿Qué ventaja tiene usar la distribución normal estándar para comparar la glucosa y el IMC de un mismo paciente?', NULL, 'Permite comparar cuál de las dos medidas es más extrema en relación con su respectiva población, a pesar de estar en unidades diferentes (mg/dL vs kg/m²).', 2, 1),
(17, '¿Qué es el error de muestreo y por qué es inevitable en estudios clínicos?', NULL, 'Es la diferencia entre un estadígrafo y el verdadero parámetro poblacional; es inevitable porque las muestras siempre tienen variabilidad aleatoria.', 2, 1),
(18, '¿Por qué se asume p = 0.5 al calcular el tamaño de muestra cuando no se conoce la proporción esperada?', NULL, 'Porque p = 0.5 maximiza el producto p·q, lo que produce el tamaño de muestra más conservador (más grande), garantizando precisión incluso en el peor caso.', 2, 1),
(19, '¿Qué diferencia hay entre muestreo estratificado y muestreo aleatorio simple, y cuándo es útil el primero?', NULL, 'En el estratificado, se divide la población en subgrupos (estratos) y se muestrea de cada uno; es útil cuando hay subpoblaciones importantes (ej.: gravedad de enfermedad).', 2, 1),
(20, '¿Por qué la ley de regularidad estadística es fundamental para la probabilidad frecuencial?', NULL, 'Porque establece que, al aumentar las observaciones, la frecuencia relativa se estabiliza en torno a la probabilidad real, dándole sentido a las estimaciones empíricas.', 2, 1),
(21, '¿Qué implica que un dato tenga un valor Z de 0 en cualquier distribución normal?', NULL, 'Que el dato coincide exactamente con la media de la distribución, ubicándose en el percentil 50.', 2, 1),
(22, '¿Por qué no se puede generalizar los resultados de un muestreo por conveniencia a toda la población?', NULL, 'Porque la muestra no es representativa: se selecciona por accesibilidad, no al azar, lo que introduce sesgo sistemático.', 2, 1),
(23, 'Si en una tabla Z, P(Z < 1.65) = 0.9505, ¿qué significa esto en términos de percentil?', NULL, 'Que un valor Z de 1.65 corresponde aproximadamente al percentil 95, es decir, el 95% de la población tiene valores menores que ese punto.', 2, 1),
(24, 'Si la talla de adultos tiene una media de 170 cm y una desviación estándar de 10 cm, ¿qué porcentaje tiene valores entre 140 y 200 cm?', NULL, 'Aproximadamente el 99.7%, porque 140 = 170 - 3×10 y 200 = 170 + 3×10, lo que corresponde a μ ± 3σ en una distribución normal.', 2, 1);

-- Grupo 6 (Números 25-36)
INSERT INTO questions (number, question, image, answer, group_id, user_id) VALUES 
(25, '¿Por qué la distribución normal es fundamental en la definición de rangos de normalidad en laboratorios clínicos?', NULL, 'Porque permite definir límites objetivos (usualmente μ ± 2σ) que incluyen al 95% de la población sana, facilitando la identificación de valores anormales.', 3, 1),
(26, '¿Qué significa que una muestra sea representativa y por qué es clave en estudios epidemiológicos?', NULL, 'Que refleja las características de la población; es clave porque solo así los resultados pueden generalizarse con validez.', 3, 1),
(27, '¿Por qué no se puede afirmar que la media muestral es exactamente igual a la media poblacional?', NULL, 'Porque la media muestral es un estadígrafo sujeto a variabilidad aleatoria; solo es una estimación del verdadero parámetro poblacional.', 3, 1),
(28, '¿Por qué es útil que la distribución normal sea un modelo teórico continuo aunque los datos reales sean discretos?', NULL, 'Porque permite calcular probabilidades para cualquier valor (ej.: 119.7 mmHg), no solo los observados, mejorando la precisión de las estimaciones.', 3, 1),
(29, '¿Qué diferencia hay entre una variable aleatoria discreta y una continua en el contexto de la salud?', NULL, 'Una discreta toma valores contables (ej.: número de hijos); una continua toma cualquier valor en un rango (ej.: peso, talla, glucosa).', 3, 1),
(30, '¿Por qué el valor Z es una medida adimensional?', NULL, 'Porque resulta de dividir una diferencia (en unidades originales) entre una desviación estándar (misma unidad), lo que elimina las unidades y permite comparaciones universales.', 3, 1),
(31, '¿Qué implica que un paciente esté en el percentil 10 de presión arterial sistólica?', NULL, 'Que el 90% de la población tiene una PAS más alta que él, lo que podría indicar hipotensión relativa.', 3, 1),
(32, '¿Por qué el muestreo aleatorio reduce el error sistemático en comparación con el no probabilístico?', NULL, 'Porque asigna igual probabilidad de selección a todos, evitando que ciertos grupos estén sobrerrepresentados o subrepresentados por decisión del investigador.', 3, 1),
(33, '¿Qué nos permite inferir un valor Z de -2.0 en los niveles de calcio sérico?', NULL, 'Que el nivel está 2 desviaciones estándar por debajo de la media, ubicándose en el percentil 2.5, lo que sugiere hipocalcemia significativa.', 3, 1),
(34, '¿Por qué la tabla Z siempre da la probabilidad acumulada a la izquierda del valor?', NULL, 'Por convención estadística; esto permite calcular cualquier probabilidad (cola derecha, entre dos valores) mediante operaciones simples con esa probabilidad acumulada.', 3, 1),
(35, '¿Por qué la tabla de valores Z siempre proporciona la probabilidad acumulada a la izquierda del valor Z, y cómo se usaría para encontrar la probabilidad de que una variable sea mayor que un valor dado?', NULL, 'Por convención, la tabla Z da el área bajo la curva a la izquierda del valor Z. Para hallar la probabilidad de que una variable sea mayor que un valor, se calcula 1 menos la probabilidad acumulada (es decir, P(X > x) = 1 - P(Z < z)).', 3, 1),
(36, 'Si la creatinina sérica tiene una media de 0.9 mg/dL y una desviación estándar de 0.2 mg/dL, ¿qué podemos decir de los valores menores a 0.5 mg/dL y mayores a 1.3 mg/dL?', NULL, 'Ambos están a más de 2 desviaciones estándar de la media (0.5 = 0.9 - 2×0.2; 1.3 = 0.9 + 2×0.2), por lo que son considerados “inusuales” o potencialmente anormales, ya que solo el 5% de la población cae fuera de ese rango.', 3, 1);